site_name: Seatsurfing
docs_dir: src
theme:
    name: material
    logo: img/icon.svg
    language: de
nav:
    - 'index.md'
    - 'features.md'
    - 'getting-started.md'
    - 'config.md'
    - 'admin-ui.md'
    - 'app.md'
    - 'booking-ui.md'
    - 'confluence.md'
    - 'permissions.md'
    - 'support.md'