site_name: Seatsurfing Documentation
docs_dir: src
theme:
    name: material
    logo: img/seatsurfing_white.svg
    language: en
extra_css:
    - stylesheets/extra.css
nav:
    - 'index.md'
    - 'features.md'
    - 'getting-started.md'
    - 'config.md'
    - 'admin-ui.md'
    - 'app.md'
    - 'booking-ui.md'
    - 'confluence.md'
    - 'rest-api.md'
    - 'support.md'