name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --pull --file Dockerfile --tag seatsurfing/docs:${GITHUB_SHA::6} --tag seatsurfing/docs:latest
